version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db_drone_deeder
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: